
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_INIT = 'POST_LOGIN_INIT';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_INIT = 'GET_USER_INIT';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_INIT = 'POST_USER_INIT';
export const POST_USER_ERROR = 'POST_USER_ERROR';

export const PUT_FAVORITE_CHARACTER_SUCCESS = 'PUT_FAVORITE_CHARACTER_SUCCESS';
export const PUT_FAVORITE_CHARACTER_INIT = 'PUT_FAVORITE_CHARACTER_INIT';
export const PUT_FAVORITE_CHARACTER_ERROR = 'PUT_FAVORITE_CHARACTER_ERROR';

export const PUT_FAVORITE_EPISODES_SUCCESS = 'PUT_FAVORITE_EPISODES_SUCCESS';
export const PUT_FAVORITE_EPISODES_INIT = 'PUT_FAVORITE_EPISODES_INIT';
export const PUT_FAVORITE_EPISODES_ERROR = 'PUT_FAVORITE_EPISODES_ERROR';