export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTER_SUCCESS';
export const GET_CHARACTERS_INIT = 'GET_CHARACTER_INIT';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTER_ERROR';
export const RELOAD_CHARACTERS = 'RELOAD_CHARACTERS';

