export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_INIT = 'GET_EPISODES_INIT';
export const GET_EPISODES_ERROR = 'GET_EPISODES_ERROR';
export const RELOAD_EPISODES = 'RELOAD_EPISODES';
